version: "3.7"
services:

    postgres:
      image: postgres:12.1
      container_name: ${APP_NAME}-postgres
      volumes:
         - "./sourcefiles/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}
      ports:
       - "5432:5432"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    webserver:
      image: nginx:alpine
      container_name: ${APP_NAME}-webserver
      working_dir: /application
      volumes:
          - ./:/application
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${APP_NAME}-php-fpm
      working_dir: /application
      volumes:
        - ./:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
          testing_net:
              ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
