version: "3.7"
services:

  postgres:
    image: postgres:12.1
    container_name: laravel-meeting-postgres
    volumes:
      - "./docker_config/postgres/data:/var/lib/postgresql/data"
      - ./docker_config/postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  nginx:
    build: docker_config/nginx
    container_name: laravel-meeting-nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www:shared,consistent
      # - ./docker_config/nginx/site:/etc/nginx/conf.d
      - ./docker_config/nginx/site:/etc/nginx/sites-available
      
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  php-fpm:
    build: docker_config/fpm
    container_name: laravel-meeting-php-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www:shared,consistent
      - ./docker_config/fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
